version: "3.9"

services:
    
  db:
    container_name: postgres-db
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/data/db

    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}    

volumes:
  node_modules:
